DROP TABLE "USER_BEN";
DROP TABLE "COFFEE_BEANS_HISTORY";
DROP TABLE "MESSAGE_IMG";
DROP TABLE "RECOMMEND_BOOKS";
DROP TABLE "BLOG_TAG";
DROP TABLE "COFFEE_BEANS_TRADE";
DROP TABLE "JOB_POSTING";
DROP TABLE "REPORT";
DROP TABLE "COFFEE_BEANS_EXCHANGE";
DROP TABLE "MESSAGE_EMOJI";
DROP TABLE "FOLLOW";
DROP TABLE "AUTH";
DROP TABLE "COFFEE_BEANS_PAY";
DROP TABLE "TAG";
DROP TABLE "REPORT_CODE";
DROP TABLE "CHATTING_USER";
DROP TABLE "CAFE_IMAGE";
DROP TABLE "MESSAGE";
DROP TABLE "COMMENT_LIKE";
DROP TABLE "VISIT_COUNT";
DROP TABLE "CB_TOKEN_USAGE";
DROP TABLE "USER_SCRAP";
DROP TABLE "SOCIAL_LOGIN";
DROP TABLE "NOTIFICATION";
DROP TABLE "BOARD_IMG";
DROP TABLE "CB_SESSION";
DROP TABLE "SUBSCRIBE";
DROP TABLE "BOARD_LIKE";
DROP TABLE "BANK_INFO";
DROP TABLE "CAFE_REVIEW_KEYWORD";
DROP TABLE "COMPANY_CODE";
DROP TABLE "RECOMMEND_CAFES";
DROP TABLE "COMMENT";
DROP TABLE "BLOG";
DROP TABLE "EMOJI";
DROP TABLE "BOARD";
DROP TABLE "CHATTING_ROOM";
DROP TABLE "MEMBER";
DROP TABLE "LEVELS";
DROP TABLE "BOARDTYPE";

-----------------------------------------------
DROP TABLE "COMPANY_CODE";

CREATE TABLE "COMPANY_CODE" (
   "COMPANY_CODE"   NUMBER      NOT NULL,
   "COMPANY_NAME"   VARCHAR2(100)      NOT NULL,
   "WORK_ADDR"   VARCHAR2(100)      NULL,
   "NEARBY_SUB"   VARCHAR2(500)      NULL
);

COMMENT ON COLUMN "COMPANY_CODE"."COMPANY_CODE" IS '회사코드번호(SEQ_NO)';

COMMENT ON COLUMN "COMPANY_CODE"."COMPANY_NAME" IS '회사명';

COMMENT ON COLUMN "COMPANY_CODE"."WORK_ADDR" IS '회사주소';

COMMENT ON COLUMN "COMPANY_CODE"."NEARBY_SUB" IS '인근지하철';

DROP TABLE "COFFEE_BEANS_HISTORY";

CREATE TABLE "COFFEE_BEANS_HISTORY" (
   "BEANS_HISTORY"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "PAY_AMOUNT"   NUMBER      NOT NULL,
   "TRADE_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "COFFEE_BEANS_HISTORY"."BEANS_HISTORY" IS '커피콩 내역';

COMMENT ON COLUMN "COFFEE_BEANS_HISTORY"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "COFFEE_BEANS_HISTORY"."PAY_AMOUNT" IS '+, -';

COMMENT ON COLUMN "COFFEE_BEANS_HISTORY"."TRADE_NO" IS 'SEQ_TRADE_NO';

DROP TABLE "MESSAGE_IMG";

CREATE TABLE "MESSAGE_IMG" (
   "MSG_IMG_NO"   NUMBER      NOT NULL,
   "IMG_PATH"   VARCHAR2(100)      NOT NULL,
   "ORIGIN_NAME"   VARCHAR2(100)      NOT NULL,
   "RENAME_NAME"   VARCHAR2(100)      NOT NULL,
   "MESSAGE_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "MESSAGE_IMG"."MSG_IMG_NO" IS '시퀀스번호';

COMMENT ON COLUMN "MESSAGE_IMG"."IMG_PATH" IS '이미지 경로';

COMMENT ON COLUMN "MESSAGE_IMG"."ORIGIN_NAME" IS '파일 원본명';

COMMENT ON COLUMN "MESSAGE_IMG"."RENAME_NAME" IS '파일 변경명';

COMMENT ON COLUMN "MESSAGE_IMG"."MESSAGE_NO" IS '시퀀스 번호';

DROP TABLE "RECOMMEND_BOOKS";

CREATE TABLE "RECOMMEND_BOOKS" (
   "BOOK_ID"   NUMBER      NOT NULL,
   "ISBN10"   VARCHAR2(30)      NULL,
   "ISBN13"   VARCHAR2(30)      NULL,
   "TITLE"   VARCHAR2(255)      NOT NULL,
   "SUBTITLE"   VARCHAR2(255)      NULL,
   "AUTHOR"   VARCHAR2(500)      NULL,
   "CATEGORY"   VARCHAR2(500)      NULL,
   "PUBLISHER"   VARCHAR2(255)      NULL,
   "PUBLISH_DATE"   DATE      NULL,
   "DESCRIPTION"   CLOB      NULL,
   "TOC"   CLOB      NULL,
   "PRICE"   NUMBER      NULL,
   "SALE_PRICE"   NUMBER      NULL,
   "COVER_IMAGE"   VARCHAR2(500)      NULL,
   "DETAIL_URL"   VARCHAR2(500)      NULL
);

COMMENT ON COLUMN "RECOMMEND_BOOKS"."BOOK_ID" IS 'SEQ_BOOK_ID';

DROP TABLE "RECOMMEND_CAFES";

CREATE TABLE "RECOMMEND_CAFES" (
   "CAFE_ID"   NUMBER      NOT NULL,
   "CAFE_NAME"   VARCHAR2(200)      NOT NULL,
   "ADDRESS"   VARCHAR2(300)      NOT NULL,
   "EXTERNAL_ID"   VARCHAR2(100)      NULL,
   "LAT"   NUMBER      NULL,
   "LNG"   NUMBER      NULL,
   "PHONE"   VARCHAR2(50)      NULL,
   "RATING"   NUMBER      NULL,
   "USER_RATING_CNT"   NUMBER      NULL,
   "WEBSITE"   VARCHAR2(300)      NULL,
   "CREATED_AT"   DATE   DEFAULT SYSDATE   NOT NULL
);

COMMENT ON COLUMN "RECOMMEND_CAFES"."CAFE_ID" IS 'SEQ_CAFE_ID';

COMMENT ON COLUMN "RECOMMEND_CAFES"."RATING" IS '2.0';

DROP TABLE "COMMENT";

CREATE TABLE "COMMENT" (
   "COMMENT_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL,
   "PARENTS_COMMENT_NO"   NUMBER      NULL,
   "C_CREATE_DATE"   DATE   DEFAULT SYSDATE   NULL,
   "COMMENT_CONTENT"   VARCHAR2(2000)      NOT NULL,
   "COMMENT_DEL_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "SECRET_YN"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "MODIFY_YN"   CHAR(1)   DEFAULT 'N'   NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글번호(SEQ_COMMENT_NO)';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "COMMENT"."PARENTS_COMMENT_NO" IS '부모 댓글 번호';

COMMENT ON COLUMN "COMMENT"."C_CREATE_DATE" IS '댓글작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글삭제여부(N: 삭제X, Y:삭제0)';

COMMENT ON COLUMN "COMMENT"."SECRET_YN" IS '비밀글 여부';

COMMENT ON COLUMN "COMMENT"."MODIFY_YN" IS '수정여부';

DROP TABLE "BLOG";

CREATE TABLE "BLOG" (
   "BOARD_NO"   NUMBER      NOT NULL,
   "IS_PAID"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "PRICE"   NUMBER      NULL,
   "TEMP_FL"   CHAR(1)   DEFAULT 'Y'   NOT NULL
);

COMMENT ON COLUMN "BLOG"."BOARD_NO" IS '게시글번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "BLOG"."IS_PAID" IS '유료 게시글 여부';

COMMENT ON COLUMN "BLOG"."PRICE" IS '가격';

COMMENT ON COLUMN "BLOG"."TEMP_FL" IS 'Y는 임시저장 N은 발행';

DROP TABLE "EMOJI";

CREATE TABLE "EMOJI" (
   "EMOJI_CODE"   NUMBER      NOT NULL,
   "EMOJI"   VARCHAR2(3)      NOT NULL
);

COMMENT ON COLUMN "EMOJI"."EMOJI_CODE" IS '이모지 코드';

DROP TABLE "BLOG_TAG";

CREATE TABLE "BLOG_TAG" (
   "BOARD_NO"   NUMBER      NOT NULL,
   "TAG_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "BLOG_TAG"."BOARD_NO" IS '게시글번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "BLOG_TAG"."TAG_NO" IS 'SEQ_TAG_NO';

DROP TABLE "BOARDTYPE";

CREATE TABLE "BOARDTYPE" (
   "BOARD_CODE"   NUMBER      NOT NULL,
   "BOARD_NAME"   VARCHAR2(20)      NOT NULL,
   "PARENTS_BOARD_CODE"   NUMBER      NULL
);

COMMENT ON COLUMN "BOARDTYPE"."BOARD_CODE" IS '게시판코드';

COMMENT ON COLUMN "BOARDTYPE"."BOARD_NAME" IS '게시판이름';

COMMENT ON COLUMN "BOARDTYPE"."PARENTS_BOARD_CODE" IS '게시판코드';

DROP TABLE "COFFEE_BEANS_TRADE";

CREATE TABLE "COFFEE_BEANS_TRADE" (
   "TRADE_NO"   NUMBER      NOT NULL,
   "BUYER_NO"   NUMBER      NOT NULL,
   "SELLER_NO"   NUMBER      NOT NULL,
   "CONTENT_TYPE"   VARCHAR2(30)      NOT NULL,
   "TRADE_AT"   DATE   DEFAULT SYSDATE   NOT NULL,
   "CONTENT_ID"   NUMBER      NULL,
   "PRICE"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "COFFEE_BEANS_TRADE"."TRADE_NO" IS 'SEQ_TRADE_NO';

COMMENT ON COLUMN "COFFEE_BEANS_TRADE"."BUYER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "COFFEE_BEANS_TRADE"."SELLER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "COFFEE_BEANS_TRADE"."CONTENT_TYPE" IS 'POST / SUBSCRIBE / CHATBOT';

COMMENT ON COLUMN "COFFEE_BEANS_TRADE"."TRADE_AT" IS '거래일시';

COMMENT ON COLUMN "COFFEE_BEANS_TRADE"."CONTENT_ID" IS '대상 ID(게시글번호,회원번호,,, 챗봇번호?)';

COMMENT ON COLUMN "COFFEE_BEANS_TRADE"."PRICE" IS '거래금액';

DROP TABLE "JOB_POSTING";

CREATE TABLE "JOB_POSTING" (
   "POSTING_NO"   NUMBER      NOT NULL,
   "POSTING_TITLE"   VARCHAR2(100)      NOT NULL,
   "POSTING_CONTENT"   CLOB      NULL,
   "REC_FIELD"   VARCHAR2(4000)      NULL,
   "REC_COUNT"   VARCHAR2(30)      NULL,
   "EMP_TYPE"   VARCHAR2(100)      NULL,
   "SALARY"   VARCHAR2(100)      NULL,
   "REQ_CAREER"   VARCHAR2(100)      NULL,
   "REQ_EDUCATION"   VARCHAR2(100)      NULL,
   "APPLY_START"   VARCHAR2(30)      NULL,
   "APPLY_END"   VARCHAR2(30)      NULL,
   "APPLY_METHOD"   VARCHAR2(30)      NULL,
   "COMPANY_CODE"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "JOB_POSTING"."POSTING_NO" IS '채용공고번호(SEQ_NO)';

COMMENT ON COLUMN "JOB_POSTING"."POSTING_TITLE" IS '공고제목';

COMMENT ON COLUMN "JOB_POSTING"."POSTING_CONTENT" IS '상세요강';

COMMENT ON COLUMN "JOB_POSTING"."REC_FIELD" IS '모집요강';

COMMENT ON COLUMN "JOB_POSTING"."REC_COUNT" IS '모집인원';

COMMENT ON COLUMN "JOB_POSTING"."EMP_TYPE" IS '고용형태';

COMMENT ON COLUMN "JOB_POSTING"."SALARY" IS '급여';

COMMENT ON COLUMN "JOB_POSTING"."REQ_CAREER" IS '경력';

COMMENT ON COLUMN "JOB_POSTING"."REQ_EDUCATION" IS '학력';

COMMENT ON COLUMN "JOB_POSTING"."APPLY_START" IS '접수시작일';

COMMENT ON COLUMN "JOB_POSTING"."APPLY_END" IS '접수마감일';

COMMENT ON COLUMN "JOB_POSTING"."APPLY_METHOD" IS '접수방법';

COMMENT ON COLUMN "JOB_POSTING"."COMPANY_CODE" IS '회사코드번호(SEQ_BOARD_NO)';

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
   "BOARD_NO"   NUMBER      NOT NULL,
   "BOARD_TITLE"   VARCHAR2(300)      NOT NULL,
   "BOARD_CONTENT"   CLOB      NOT NULL,
   "B_CREATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "B_UPDATE_DATE"   DATE      NULL,
   "BOARD_COUNT"   NUMBER   DEFAULT 0   NOT NULL,
   "BOARD_DEL_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "BOARD_CODE"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "NEWS_REPORTER"   VARCHAR2(100)      NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글내용';

COMMENT ON COLUMN "BOARD"."B_CREATE_DATE" IS '게시글작성일';

COMMENT ON COLUMN "BOARD"."B_UPDATE_DATE" IS '게시글최종수정일';

COMMENT ON COLUMN "BOARD"."BOARD_COUNT" IS '게시글조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글삭제여부';

COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판코드';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "BOARD"."NEWS_REPORTER" IS '기자명';

DROP TABLE "REPORT";

CREATE TABLE "REPORT" (
   "REPORT_ID"   NUMBER      NOT NULL,
   "TARGET_TYPE"   VARCHAR2(15)      NOT NULL,
   "CONTENT"   VARCHAR2(300)      NULL,
   "TARGET_ID"   NUMBER      NOT NULL,
   "MESSAGE_CONTENT"   VARCHAR2(4000)      NULL,
   "CREATED_AT"   DATE   DEFAULT SYSDATE   NOT NULL,
   "PROCESSED_AT"   DATE      NULL,
   "STATUS"   VARCHAR2(15)      NOT NULL,
   "REPORTER_NO"   NUMBER      NOT NULL,
   "REPORTED_NO"   NUMBER      NOT NULL,
   "REPORT_CODE"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_ID" IS '시퀀스 번호';

COMMENT ON COLUMN "REPORT"."TARGET_TYPE" IS '게시글/메세지';

COMMENT ON COLUMN "REPORT"."CONTENT" IS '신고 상세 사유';

COMMENT ON COLUMN "REPORT"."TARGET_ID" IS '신고 대상 번호';

COMMENT ON COLUMN "REPORT"."REPORTER_NO" IS '신고한 회원';

COMMENT ON COLUMN "REPORT"."REPORTED_NO" IS '신고 당한 회원';

COMMENT ON COLUMN "REPORT"."REPORT_CODE" IS '신고 유형 코드';

DROP TABLE "COFFEE_BEANS_EXCHANGE";

CREATE TABLE "COFFEE_BEANS_EXCHANGE" (
   "EXCHANGE_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "RETURN_BANK"   VARCHAR2(10)      NOT NULL,
   "REQUEST_AMOUNT"   NUMBER      NOT NULL,
   "EXCHANGE_HOLDER"   VARCHAR2(100)      NOT NULL,
   "EXCHANGE_ACCOUNT"   VARCHAR2(100)      NOT NULL,
   "EXCHANGE_REQ_DATE"   DATE      NOT NULL,
   "EXCHANGE_OK_DATE"   DATE      NULL
);

COMMENT ON COLUMN "COFFEE_BEANS_EXCHANGE"."EXCHANGE_NO" IS 'SEQ_EXCHANGE_NO';

COMMENT ON COLUMN "COFFEE_BEANS_EXCHANGE"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "COFFEE_BEANS_EXCHANGE"."RETURN_BANK" IS '은행코드';

COMMENT ON COLUMN "COFFEE_BEANS_EXCHANGE"."REQUEST_AMOUNT" IS '환전요청금액';

COMMENT ON COLUMN "COFFEE_BEANS_EXCHANGE"."EXCHANGE_HOLDER" IS '예금주';

COMMENT ON COLUMN "COFFEE_BEANS_EXCHANGE"."EXCHANGE_ACCOUNT" IS '환전계좌번호';

COMMENT ON COLUMN "COFFEE_BEANS_EXCHANGE"."EXCHANGE_REQ_DATE" IS '환전요청일시';

COMMENT ON COLUMN "COFFEE_BEANS_EXCHANGE"."EXCHANGE_OK_DATE" IS '환전처리일시';

DROP TABLE "MESSAGE_EMOJI";

CREATE TABLE "MESSAGE_EMOJI" (
   "REACTION_NO"   NUMBER      NOT NULL,
   "MESSAGE_NO"   NUMBER      NOT NULL,
   "EMOJI_CODE"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "MESSAGE_EMOJI"."REACTION_NO" IS '시퀀스 번호';

COMMENT ON COLUMN "MESSAGE_EMOJI"."MESSAGE_NO" IS '시퀀스 번호';

COMMENT ON COLUMN "MESSAGE_EMOJI"."EMOJI_CODE" IS '이모지 코드';

COMMENT ON COLUMN "MESSAGE_EMOJI"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

DROP TABLE "FOLLOW";

CREATE TABLE "FOLLOW" (
   "FOLLOW_ID"   NUMBER      NOT NULL,
   "FOLLOWED_ID"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "FOLLOW"."FOLLOW_ID" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "FOLLOW"."FOLLOWED_ID" IS '회원번호(SEQ_MEMBER_NO)';

DROP TABLE "CHATTING_ROOM";

CREATE TABLE "CHATTING_ROOM" (
   "CHATTING_ROOM_NO"   NUMBER      NOT NULL,
   "CHATTING_ROOM_NAME"   VARCHAR2(50)      NOT NULL,
   "CREATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "ROOM_TYPE"   VARCHAR2(30)      NOT NULL
);

COMMENT ON COLUMN "CHATTING_ROOM"."CHATTING_ROOM_NO" IS '채팅방 시퀀스 번호';

COMMENT ON COLUMN "CHATTING_ROOM"."CHATTING_ROOM_NAME" IS '개인 톡 : 상대방 이름, 단체톡 : 톡방이름';

COMMENT ON COLUMN "CHATTING_ROOM"."CREATE_DATE" IS '채팅방 생성 날짜';

COMMENT ON COLUMN "CHATTING_ROOM"."ROOM_TYPE" IS 'PRIVATE, GROUP';

DROP TABLE "AUTH";

CREATE TABLE "AUTH" (
   "AUTH_NO"   NUMBER      NOT NULL,
   "CODE"   VARCHAR2(100)      NOT NULL,
   "EMAIL"   VARCHAR2(100)      NOT NULL,
   "CREATE_AT"   DATE   DEFAULT SYSDATE   NOT NULL
);

COMMENT ON COLUMN "AUTH"."AUTH_NO" IS '시퀀스번호';

COMMENT ON COLUMN "AUTH"."CODE" IS '인증키 코드';

COMMENT ON COLUMN "AUTH"."EMAIL" IS '이메일';

COMMENT ON COLUMN "AUTH"."CREATE_AT" IS '생성시간';

DROP TABLE "COFFEE_BEANS_PAY";

CREATE TABLE "COFFEE_BEANS_PAY" (
   "BEANS_PAY_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "PAYMENT_ID"   VARCHAR2(30)      NOT NULL,
   "PAY_METHOD"   VARCHAR2(20)      NULL,
   "PRICE"   NUMBER      NOT NULL,
   "PAY_DATE"   DATE      NOT NULL,
   "USED_AMOUNT"   NUMBER      NOT NULL,
   "PAY_STATUS"   CHAR(1)      NOT NULL
);

COMMENT ON COLUMN "COFFEE_BEANS_PAY"."BEANS_PAY_NO" IS '결제 번호(SEQ_PAY_NO)';

COMMENT ON COLUMN "COFFEE_BEANS_PAY"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "COFFEE_BEANS_PAY"."PAYMENT_ID" IS '난수(포트원으로 넘겨주는고유번호 )';

COMMENT ON COLUMN "COFFEE_BEANS_PAY"."PAY_METHOD" IS '카드, 간편결제 등등';

COMMENT ON COLUMN "COFFEE_BEANS_PAY"."PRICE" IS '결제금액';

COMMENT ON COLUMN "COFFEE_BEANS_PAY"."PAY_DATE" IS '결제일시';

COMMENT ON COLUMN "COFFEE_BEANS_PAY"."USED_AMOUNT" IS 'USED_AMOUNT>0 취소불가';

COMMENT ON COLUMN "COFFEE_BEANS_PAY"."PAY_STATUS" IS '1:충전 2:환불(취소)';

DROP TABLE "TAG";

CREATE TABLE "TAG" (
   "TAG_NO"   NUMBER      NOT NULL,
   "TAG_NAME"   VARCHAR2(100)      NOT NULL
);

COMMENT ON COLUMN "TAG"."TAG_NO" IS 'SEQ_TAG_NO';

COMMENT ON COLUMN "TAG"."TAG_NAME" IS '태그이름';

DROP TABLE "REPORT_CODE";

CREATE TABLE "REPORT_CODE" (
   "REPORT_CODE"   NUMBER      NOT NULL,
   "REPORT_TYPE"   VARCHAR2(100)      NOT NULL
);

COMMENT ON COLUMN "REPORT_CODE"."REPORT_TYPE" IS '신고 유형 타입';

DROP TABLE "CHATTING_USER";

CREATE TABLE "CHATTING_USER" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "CHATTING_ROOM_NO"   NUMBER      NOT NULL,
   "PINNED_YN"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "JOIN_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "ROLE"   VARCHAR2(30)      NOT NULL,
   "LAST_READ_NO"   NUMBER      NULL
);

COMMENT ON COLUMN "CHATTING_USER"."CHATTING_ROOM_NO" IS '채팅방 시퀀스 번호';

COMMENT ON COLUMN "CHATTING_USER"."PINNED_YN" IS '채팅방 고정여부';

COMMENT ON COLUMN "CHATTING_USER"."JOIN_DATE" IS '채팅방 참여일';

COMMENT ON COLUMN "CHATTING_USER"."ROLE" IS 'OWNER, MEMBER';

COMMENT ON COLUMN "CHATTING_USER"."LAST_READ_NO" IS '마지막으로 읽은 메세지 번호';

DROP TABLE "CAFE_IMAGE";

CREATE TABLE "CAFE_IMAGE" (
   "IMAGE_ID"   NUMBER      NOT NULL,
   "CAFE_ID"   NUMBER      NOT NULL,
   "PHOTO_REFERENCE"   VARCHAR2(300)      NULL,
   "SORT_ORDER"   NUMBER      NULL,
   "CREATED_AT"   DATE   DEFAULT SYSDATE   NOT NULL
);

COMMENT ON COLUMN "CAFE_IMAGE"."CAFE_ID" IS 'SEQ_CAFE_ID';

COMMENT ON COLUMN "CAFE_IMAGE"."SORT_ORDER" IS '대표이미지:1';

DROP TABLE "MESSAGE";

CREATE TABLE "MESSAGE" (
   "MESSAGE_NO"   NUMBER      NOT NULL,
   "CHATTING_ROOM_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "SEND_TIME"   DATE   DEFAULT SYSDATE   NOT NULL,
   "TYPE"   VARCHAR2(20)      NOT NULL,
   "MESSAGE_CONTENT"   VARCHAR2(3000)      NULL,
   "MESSAGE_STATUS"   VARCHAR2(30)      NULL
);

COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS '시퀀스 번호';

COMMENT ON COLUMN "MESSAGE"."CHATTING_ROOM_NO" IS '채팅방 시퀀스 번호';

COMMENT ON COLUMN "MESSAGE"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MESSAGE"."SEND_TIME" IS '메세지 보낸 시간';

COMMENT ON COLUMN "MESSAGE"."TYPE" IS 'IMG, SYSTEM, TEXT';

COMMENT ON COLUMN "MESSAGE"."MESSAGE_CONTENT" IS '메세지 내용';

COMMENT ON COLUMN "MESSAGE"."MESSAGE_STATUS" IS '수정/삭제';

DROP TABLE "COMMENT_LIKE";

CREATE TABLE "COMMENT_LIKE" (
   "COMMENT_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "STATUS"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "COMMENT_LIKE"."COMMENT_NO" IS '댓글번호(SEQ_COMMENT_NO)';

COMMENT ON COLUMN "COMMENT_LIKE"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "COMMENT_LIKE"."STATUS" IS '1 : 좋아요 2 : 싫어요';

DROP TABLE "VISIT_COUNT";

CREATE TABLE "VISIT_COUNT" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "TOTAL_VISIT"   NUMBER      NOT NULL,
   "DAILY_VISIT"   NUMBER      NOT NULL,
   "LAST_DATE"   DATE   DEFAULT SYSDATE   NOT NULL
);

COMMENT ON COLUMN "VISIT_COUNT"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "VISIT_COUNT"."TOTAL_VISIT" IS '전방';

COMMENT ON COLUMN "VISIT_COUNT"."DAILY_VISIT" IS '오망';

COMMENT ON COLUMN "VISIT_COUNT"."LAST_DATE" IS '오늘 방문자 수 초기화 용';

DROP TABLE "CB_TOKEN_USAGE";

CREATE TABLE "CB_TOKEN_USAGE" (
   "TK_USAGE_ID"   NUMBER      NOT NULL,
   "PROMPT_TEXT"   CLOB      NULL,
   "ANSWER_TEXT"   CLOB      NULL,
   "PROMPT_TOKENS"   NUMBER      NOT NULL,
   "ANSWER_TOKENS"   NUMBER      NOT NULL,
   "TOTAL_TOKENTS"   NUMBER      NOT NULL,
   "BEAN_SWE"   NUMBER      NULL,
   "MODEL_NAME"   VARCHAR2(50)      NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "CB_SESSION_ID"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CB_TOKEN_USAGE"."TK_USAGE_ID" IS '토큰사용이력식별자(SEQ_TOKEN_USAGE_NO)';

COMMENT ON COLUMN "CB_TOKEN_USAGE"."PROMPT_TEXT" IS '사용자질문내용';

COMMENT ON COLUMN "CB_TOKEN_USAGE"."ANSWER_TEXT" IS '챗봇대답내용';

COMMENT ON COLUMN "CB_TOKEN_USAGE"."PROMPT_TOKENS" IS '사용자질문토큰수';

COMMENT ON COLUMN "CB_TOKEN_USAGE"."ANSWER_TOKENS" IS '챗봇대답토큰수';

COMMENT ON COLUMN "CB_TOKEN_USAGE"."TOTAL_TOKENTS" IS '전체토큰수(/세션)';

COMMENT ON COLUMN "CB_TOKEN_USAGE"."BEAN_SWE" IS '과금커피콩포인트SWEngineering';

COMMENT ON COLUMN "CB_TOKEN_USAGE"."MODEL_NAME" IS '챗봇이름(GPT-4o-mini)';

COMMENT ON COLUMN "CB_TOKEN_USAGE"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "CB_TOKEN_USAGE"."CB_SESSION_ID" IS '챗봇세션식별자(SEQ_CB_SESSION_NO)';

DROP TABLE "USER_SCRAP";

CREATE TABLE "USER_SCRAP" (
   "SCRAP_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "TYPE"   VARCHAR2(20)      NOT NULL,
   "TARGET_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "USER_SCRAP"."SCRAP_NO" IS 'SEQ_SCRAP_NO';

COMMENT ON COLUMN "USER_SCRAP"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "USER_SCRAP"."TYPE" IS '1:게시글/2:채용공고';

COMMENT ON COLUMN "USER_SCRAP"."TARGET_NO" IS '게시글번호';

DROP TABLE "SOCIAL_LOGIN";

CREATE TABLE "SOCIAL_LOGIN" (
   "SOCIAL_NO"   NUMBER      NOT NULL,
   "PROVIDER"   VARCHAR2(30)      NOT NULL,
   "PROVIDER_ID"   VARCHAR2(100)      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "SOCIAL_LOGIN"."SOCIAL_NO" IS '시퀀스번호';

COMMENT ON COLUMN "SOCIAL_LOGIN"."PROVIDER" IS 'KAKAO';

COMMENT ON COLUMN "SOCIAL_LOGIN"."PROVIDER_ID" IS '식별 아이디';

COMMENT ON COLUMN "SOCIAL_LOGIN"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

DROP TABLE "NOTIFICATION";

CREATE TABLE "NOTIFICATION" (
   "NOTIFICATION_NO"   NUMBER      NOT NULL,
   "SEND_MEMBER_NO"   NUMBER      NOT NULL,
   "RECEIVE_MEMBER_NO"   NUMBER      NOT NULL,
   "CREATE_AT"   DATE   DEFAULT SYSDATE   NOT NULL,
   "IS_READ"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "CONTENT"   VARCHAR2(300)      NOT NULL,
   "TYPE"   VARCHAR2(30)      NOT NULL,
   "TARGET_TYPE"   VARCHAR2(30)      NOT NULL,
   "TARGET_ID"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_NO" IS '시퀀스번호';

COMMENT ON COLUMN "NOTIFICATION"."SEND_MEMBER_NO" IS '보낸 회원 번호';

COMMENT ON COLUMN "NOTIFICATION"."RECEIVE_MEMBER_NO" IS '받는 회원 번호';

COMMENT ON COLUMN "NOTIFICATION"."CREATE_AT" IS '생성 시간';

COMMENT ON COLUMN "NOTIFICATION"."IS_READ" IS 'Y N';

COMMENT ON COLUMN "NOTIFICATION"."CONTENT" IS '알림 메세지';

COMMENT ON COLUMN "NOTIFICATION"."TARGET_ID" IS '타겟 대상 아이디';

DROP TABLE "BOARD_IMG";

CREATE TABLE "BOARD_IMG" (
   "IMG_NO"   NUMBER      NOT NULL,
   "IMG_PATH"   VARCHAR2(500)      NOT NULL,
   "IMG_ORIG"   VARCHAR2(200)      NULL,
   "IMG_RENAME"   VARCHAR2(200)      NULL,
   "IMG_ORDER"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지번호(SEQ_IMAGE_NO)';

COMMENT ON COLUMN "BOARD_IMG"."IMG_PATH" IS '이미지경로';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIG" IS '원본이미지명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_RENAME" IS '변경이미지명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORDER" IS '이미지파일순서번호';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글번호(SEQ_BOARD_NO)';

DROP TABLE "CB_SESSION";

CREATE TABLE "CB_SESSION" (
   "CB_SESSION_ID"   NUMBER      NOT NULL,
   "STARTED_AT"   DATE   DEFAULT SYSDATE   NULL,
   "ENDED_AT"   DATE      NULL,
   "CB_SESSION_TYPE"   VARCHAR2(50)      NOT NULL,
   "CB_BOARD_TYPE"   VARCHAR2(100)      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NULL
);

COMMENT ON COLUMN "CB_SESSION"."CB_SESSION_ID" IS '챗봇세션식별자(SEQ_CB_SESSION_NO)';

COMMENT ON COLUMN "CB_SESSION"."STARTED_AT" IS '챗봇팝업시작시간';

COMMENT ON COLUMN "CB_SESSION"."ENDED_AT" IS '챗봇팝업마침시간';

COMMENT ON COLUMN "CB_SESSION"."CB_SESSION_TYPE" IS '챗봇세션유형(BASIC 기본형, BEAN 커피콩충전형)';

COMMENT ON COLUMN "CB_SESSION"."CB_BOARD_TYPE" IS '게시글유형(INSERT 또는UPDATE)';

COMMENT ON COLUMN "CB_SESSION"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "CB_SESSION"."BOARD_NO" IS '게시글번호(글쓰기:NULL/board_no), BOARD_NO:글수정)';

DROP TABLE "SUBSCRIBE";

CREATE TABLE "SUBSCRIBE" (
   "SUBSCRIBE_NO"   NUMBER      NOT NULL,
   "SUBSCRIBER_ID"   NUMBER      NOT NULL,
   "CREATOR_ID"   NUMBER      NOT NULL,
   "START_AT"   DATE   DEFAULT SYSDATE   NOT NULL
);

COMMENT ON COLUMN "SUBSCRIBE"."SUBSCRIBE_NO" IS '구독 고유 번호';

COMMENT ON COLUMN "SUBSCRIBE"."SUBSCRIBER_ID" IS '구독한 사람 회원 번호';

COMMENT ON COLUMN "SUBSCRIBE"."CREATOR_ID" IS '구독 대상';

COMMENT ON COLUMN "SUBSCRIBE"."START_AT" IS '구독 시작일';

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "MEMBER_EMAIL"   VARCHAR2(30)      NOT NULL,
   "MEMBER_PW"   VARCHAR2(200)      NULL,
   "MEMBER_NAME"   VARCHAR2(30)      NOT NULL,
   "MEMBER_NICKNAME"   VARCHAR2(30)      NOT NULL,
   "MEMBER_TEL"   VARCHAR2(13)      NOT NULL,
   "MEMBER_CAREER"   VARCHAR2(50)      NOT NULL,
   "MEMBER_SUBSCRIBE"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "MEMBER_ADMIN"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "PROFILE_IMG"   VARCHAR2(300)      NULL,
   "MEMBER_DEL_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "M_CREATE_DATE"   DATE   DEFAULT SYSDATE   NULL,
   "SUBSCRIPTION_PRICE"   NUMBER   DEFAULT 0   NOT NULL,
   "MY_INFO_INTRO"   VARCHAR2(2000)      NULL,
   "MY_INFO_GIT"   VARCHAR2(200)      NULL,
   "MY_INFO_HOMEPAGE"   VARCHAR2(200)      NULL,
   "BEANS_AMOUNT"   NUMBER   DEFAULT 0   NOT NULL,
   "CURRENT_EXP"   NUMBER   DEFAULT 0   NOT NULL,
   "MEMBER_LEVEL"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원이메일(아이디)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_CAREER" IS '회원경력사항';

COMMENT ON COLUMN "MEMBER"."MEMBER_SUBSCRIBE" IS '회원전용메일수신동의';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADMIN" IS '관리자계정여부(Y:관리자, N:일반회원)';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원탈퇴여부';

COMMENT ON COLUMN "MEMBER"."M_CREATE_DATE" IS '회원가입일';

COMMENT ON COLUMN "MEMBER"."SUBSCRIPTION_PRICE" IS '나를구독하면 지불해야할금액: 초기값0원';

COMMENT ON COLUMN "MEMBER"."MY_INFO_INTRO" IS '내 소개글';

COMMENT ON COLUMN "MEMBER"."MY_INFO_GIT" IS '깃허브 주소';

COMMENT ON COLUMN "MEMBER"."MY_INFO_HOMEPAGE" IS '노션, 포트폴리오 등 주소';

COMMENT ON COLUMN "MEMBER"."BEANS_AMOUNT" IS '커피콩지갑';

COMMENT ON COLUMN "MEMBER"."CURRENT_EXP" IS '회원 현재 경험치';

COMMENT ON COLUMN "MEMBER"."MEMBER_LEVEL" IS 'LV1 ~ LV30';

DROP TABLE "BOARD_LIKE";

CREATE TABLE "BOARD_LIKE" (
   "BOARD_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '게시글번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

DROP TABLE "LEVELS";

CREATE TABLE "LEVELS" (
   "LEVEL_NO"   NUMBER      NOT NULL,
   "REQUIRED_TOTAL_EXP"   NUMBER      NOT NULL,
   "TITLE"   VARCHAR2(100)      NOT NULL
);

COMMENT ON COLUMN "LEVELS"."LEVEL_NO" IS 'LV1 ~ LV30 (SEQ_LEVEL_NO)';

COMMENT ON COLUMN "LEVELS"."REQUIRED_TOTAL_EXP" IS '레벨별 필요 누적 경험치';

COMMENT ON COLUMN "LEVELS"."TITLE" IS '레벨별 타이틀';

DROP TABLE "BANK_INFO";

CREATE TABLE "BANK_INFO" (
   "RETURN_BANK"   VARCHAR2(10)      NOT NULL,
   "BANK_NAME"   VARCHAR2(30)      NOT NULL
);

COMMENT ON COLUMN "BANK_INFO"."RETURN_BANK" IS '은행코드';

COMMENT ON COLUMN "BANK_INFO"."BANK_NAME" IS '은행명';

DROP TABLE "CAFE_REVIEW_KEYWORD";

CREATE TABLE "CAFE_REVIEW_KEYWORD" (
   "KEYWORD_ID"   NUMBER      NOT NULL,
   "CAFE_ID"   NUMBER      NOT NULL,
   "KEYWORD"   VARCHAR2(100)      NOT NULL,
   "MENTION_CNT"   NUMBER      NULL,
   "SCORE_SUM"   NUMBER      NULL,
   "CREATED_AT"   DATE   DEFAULT SYSDATE   NOT NULL
);

COMMENT ON COLUMN "CAFE_REVIEW_KEYWORD"."CAFE_ID" IS 'SEQ_CAFE_ID';

ALTER TABLE "COMPANY_CODE" ADD CONSTRAINT "PK_COMPANY_CODE" PRIMARY KEY (
   "COMPANY_CODE"
);

ALTER TABLE "COFFEE_BEANS_HISTORY" ADD CONSTRAINT "PK_COFFEE_BEANS_HISTORY" PRIMARY KEY (
   "BEANS_HISTORY"
);

ALTER TABLE "MESSAGE_IMG" ADD CONSTRAINT "PK_MESSAGE_IMG" PRIMARY KEY (
   "MSG_IMG_NO"
);

ALTER TABLE "RECOMMEND_BOOKS" ADD CONSTRAINT "PK_RECOMMEND_BOOKS" PRIMARY KEY (
   "BOOK_ID"
);

ALTER TABLE "RECOMMEND_CAFES" ADD CONSTRAINT "PK_RECOMMEND_CAFES" PRIMARY KEY (
   "CAFE_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
   "COMMENT_NO"
);

ALTER TABLE "BLOG" ADD CONSTRAINT "PK_BLOG" PRIMARY KEY (
   "BOARD_NO"
);

ALTER TABLE "EMOJI" ADD CONSTRAINT "PK_EMOJI" PRIMARY KEY (
   "EMOJI_CODE"
);

ALTER TABLE "BLOG_TAG" ADD CONSTRAINT "PK_BLOG_TAG" PRIMARY KEY (
   "BOARD_NO",
   "TAG_NO"
);

ALTER TABLE "BOARDTYPE" ADD CONSTRAINT "PK_BOARDTYPE" PRIMARY KEY (
   "BOARD_CODE"
);

ALTER TABLE "COFFEE_BEANS_TRADE" ADD CONSTRAINT "PK_COFFEE_BEANS_TRADE" PRIMARY KEY (
   "TRADE_NO"
);

ALTER TABLE "JOB_POSTING" ADD CONSTRAINT "PK_JOB_POSTING" PRIMARY KEY (
   "POSTING_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
   "BOARD_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
   "REPORT_ID"
);

ALTER TABLE "COFFEE_BEANS_EXCHANGE" ADD CONSTRAINT "PK_COFFEE_BEANS_EXCHANGE" PRIMARY KEY (
   "EXCHANGE_NO"
);

ALTER TABLE "MESSAGE_EMOJI" ADD CONSTRAINT "PK_MESSAGE_EMOJI" PRIMARY KEY (
   "REACTION_NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY (
   "FOLLOW_ID"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "PK_CHATTING_ROOM" PRIMARY KEY (
   "CHATTING_ROOM_NO"
);

ALTER TABLE "AUTH" ADD CONSTRAINT "PK_AUTH" PRIMARY KEY (
   "AUTH_NO"
);

ALTER TABLE "COFFEE_BEANS_PAY" ADD CONSTRAINT "PK_COFFEE_BEANS_PAY" PRIMARY KEY (
   "BEANS_PAY_NO"
);

ALTER TABLE "TAG" ADD CONSTRAINT "PK_TAG" PRIMARY KEY (
   "TAG_NO"
);

ALTER TABLE "REPORT_CODE" ADD CONSTRAINT "PK_REPORT_CODE" PRIMARY KEY (
   "REPORT_CODE"
);

ALTER TABLE "CHATTING_USER" ADD CONSTRAINT "PK_CHATTING_USER" PRIMARY KEY (
   "MEMBER_NO",
   "CHATTING_ROOM_NO"
);

ALTER TABLE "CAFE_IMAGE" ADD CONSTRAINT "PK_CAFE_IMAGE" PRIMARY KEY (
   "IMAGE_ID",
   "CAFE_ID"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
   "MESSAGE_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "PK_COMMENT_LIKE" PRIMARY KEY (
   "COMMENT_NO",
   "MEMBER_NO"
);

ALTER TABLE "VISIT_COUNT" ADD CONSTRAINT "PK_VISIT_COUNT" PRIMARY KEY (
   "MEMBER_NO"
);

ALTER TABLE "CB_TOKEN_USAGE" ADD CONSTRAINT "PK_CB_TOKEN_USAGE" PRIMARY KEY (
   "TK_USAGE_ID"
);

ALTER TABLE "USER_SCRAP" ADD CONSTRAINT "PK_USER_SCRAP" PRIMARY KEY (
   "SCRAP_NO"
);

ALTER TABLE "SOCIAL_LOGIN" ADD CONSTRAINT "PK_SOCIAL_LOGIN" PRIMARY KEY (
   "SOCIAL_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY (
   "NOTIFICATION_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
   "IMG_NO"
);

ALTER TABLE "CB_SESSION" ADD CONSTRAINT "PK_CB_SESSION" PRIMARY KEY (
   "CB_SESSION_ID"
);

ALTER TABLE "SUBSCRIBE" ADD CONSTRAINT "PK_SUBSCRIBE" PRIMARY KEY (
   "SUBSCRIBE_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
   "MEMBER_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "PK_BOARD_LIKE" PRIMARY KEY (
   "BOARD_NO",
   "MEMBER_NO"
);

ALTER TABLE "LEVELS" ADD CONSTRAINT "PK_LEVELS" PRIMARY KEY (
   "LEVEL_NO"
);

ALTER TABLE "BANK_INFO" ADD CONSTRAINT "PK_BANK_INFO" PRIMARY KEY (
   "RETURN_BANK"
);

ALTER TABLE "CAFE_REVIEW_KEYWORD" ADD CONSTRAINT "PK_CAFE_REVIEW_KEYWORD" PRIMARY KEY (
   "KEYWORD_ID",
   "CAFE_ID"
);

ALTER TABLE "COFFEE_BEANS_HISTORY" ADD CONSTRAINT "FK_MEMBER_TO_COFFEE_BEANS_HISTORY_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "COFFEE_BEANS_HISTORY" ADD CONSTRAINT "FK_COFFEE_BEANS_TRADE_TO_COFFEE_BEANS_HISTORY_1" FOREIGN KEY (
   "TRADE_NO"
)
REFERENCES "COFFEE_BEANS_TRADE" (
   "TRADE_NO"
);

ALTER TABLE "MESSAGE_IMG" ADD CONSTRAINT "FK_MESSAGE_TO_MESSAGE_IMG_1" FOREIGN KEY (
   "MESSAGE_NO"
)
REFERENCES "MESSAGE" (
   "MESSAGE_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
   "PARENTS_COMMENT_NO"
)
REFERENCES "COMMENT" (
   "COMMENT_NO"
);

ALTER TABLE "BLOG" ADD CONSTRAINT "FK_BOARD_TO_BLOG_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "BLOG_TAG" ADD CONSTRAINT "FK_BLOG_TO_BLOG_TAG_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BLOG" (
   "BOARD_NO"
);

ALTER TABLE "BLOG_TAG" ADD CONSTRAINT "FK_TAG_TO_BLOG_TAG_1" FOREIGN KEY (
   "TAG_NO"
)
REFERENCES "TAG" (
   "TAG_NO"
);

ALTER TABLE "BOARDTYPE" ADD CONSTRAINT "FK_BOARDTYPE_TO_BOARDTYPE_1" FOREIGN KEY (
   "PARENTS_BOARD_CODE"
)
REFERENCES "BOARDTYPE" (
   "BOARD_CODE"
);

ALTER TABLE "COFFEE_BEANS_TRADE" ADD CONSTRAINT "FK_MEMBER_TO_COFFEE_BEANS_TRADE_1" FOREIGN KEY (
   "BUYER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "COFFEE_BEANS_TRADE" ADD CONSTRAINT "FK_MEMBER_TO_COFFEE_BEANS_TRADE_2" FOREIGN KEY (
   "SELLER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "JOB_POSTING" ADD CONSTRAINT "FK_COMPANY_CODE_TO_JOB_POSTING_1" FOREIGN KEY (
   "COMPANY_CODE"
)
REFERENCES "COMPANY_CODE" (
   "COMPANY_CODE"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARDTYPE_TO_BOARD_1" FOREIGN KEY (
   "BOARD_CODE"
)
REFERENCES "BOARDTYPE" (
   "BOARD_CODE"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
   "REPORTER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_2" FOREIGN KEY (
   "REPORTED_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_REPORT_CODE_TO_REPORT_1" FOREIGN KEY (
   "REPORT_CODE"
)
REFERENCES "REPORT_CODE" (
   "REPORT_CODE"
);

ALTER TABLE "COFFEE_BEANS_EXCHANGE" ADD CONSTRAINT "FK_MEMBER_TO_COFFEE_BEANS_EXCHANGE_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "COFFEE_BEANS_EXCHANGE" ADD CONSTRAINT "FK_BANK_INFO_TO_COFFEE_BEANS_EXCHANGE_1" FOREIGN KEY (
   "RETURN_BANK"
)
REFERENCES "BANK_INFO" (
   "RETURN_BANK"
);

ALTER TABLE "MESSAGE_EMOJI" ADD CONSTRAINT "FK_MESSAGE_TO_MESSAGE_EMOJI_1" FOREIGN KEY (
   "MESSAGE_NO"
)
REFERENCES "MESSAGE" (
   "MESSAGE_NO"
);

ALTER TABLE "MESSAGE_EMOJI" ADD CONSTRAINT "FK_EMOJI_TO_MESSAGE_EMOJI_1" FOREIGN KEY (
   "EMOJI_CODE"
)
REFERENCES "EMOJI" (
   "EMOJI_CODE"
);

ALTER TABLE "MESSAGE_EMOJI" ADD CONSTRAINT "FK_MEMBER_TO_MESSAGE_EMOJI_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOW_1" FOREIGN KEY (
   "FOLLOW_ID"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOW_2" FOREIGN KEY (
   "FOLLOWED_ID"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "COFFEE_BEANS_PAY" ADD CONSTRAINT "FK_MEMBER_TO_COFFEE_BEANS_PAY_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "CHATTING_USER" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_USER_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "CHATTING_USER" ADD CONSTRAINT "FK_CHATTING_ROOM_TO_CHATTING_USER_1" FOREIGN KEY (
   "CHATTING_ROOM_NO"
)
REFERENCES "CHATTING_ROOM" (
   "CHATTING_ROOM_NO"
);

ALTER TABLE "CAFE_IMAGE" ADD CONSTRAINT "FK_RECOMMEND_CAFES_TO_CAFE_IMAGE_1" FOREIGN KEY (
   "CAFE_ID"
)
REFERENCES "RECOMMEND_CAFES" (
   "CAFE_ID"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_CHATTING_ROOM_TO_MESSAGE_1" FOREIGN KEY (
   "CHATTING_ROOM_NO"
)
REFERENCES "CHATTING_ROOM" (
   "CHATTING_ROOM_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_MEMBER_TO_MESSAGE_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_LIKE_1" FOREIGN KEY (
   "COMMENT_NO"
)
REFERENCES "COMMENT" (
   "COMMENT_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_LIKE_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "VISIT_COUNT" ADD CONSTRAINT "FK_MEMBER_TO_VISIT_COUNT_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "CB_TOKEN_USAGE" ADD CONSTRAINT "FK_MEMBER_TO_CB_TOKEN_USAGE_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "CB_TOKEN_USAGE" ADD CONSTRAINT "FK_CB_SESSION_TO_CB_TOKEN_USAGE_1" FOREIGN KEY (
   "CB_SESSION_ID"
)
REFERENCES "CB_SESSION" (
   "CB_SESSION_ID"
);

ALTER TABLE "USER_SCRAP" ADD CONSTRAINT "FK_MEMBER_TO_USER_SCRAP_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "SOCIAL_LOGIN" ADD CONSTRAINT "FK_MEMBER_TO_SOCIAL_LOGIN_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_1" FOREIGN KEY (
   "SEND_MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_2" FOREIGN KEY (
   "RECEIVE_MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "CB_SESSION" ADD CONSTRAINT "FK_MEMBER_TO_CB_SESSION_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "CB_SESSION" ADD CONSTRAINT "FK_BOARD_TO_CB_SESSION_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "SUBSCRIBE" ADD CONSTRAINT "FK_MEMBER_TO_SUBSCRIBE_1" FOREIGN KEY (
   "SUBSCRIBER_ID"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "SUBSCRIBE" ADD CONSTRAINT "FK_MEMBER_TO_SUBSCRIBE_2" FOREIGN KEY (
   "CREATOR_ID"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_LEVELS_TO_MEMBER_1" FOREIGN KEY (
   "MEMBER_LEVEL"
)
REFERENCES "LEVELS" (
   "LEVEL_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_LIKE_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_LIKE_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "CAFE_REVIEW_KEYWORD" ADD CONSTRAINT "FK_RECOMMEND_CAFES_TO_CAFE_REVIEW_KEYWORD_1" FOREIGN KEY (
   "CAFE_ID"
)
REFERENCES "RECOMMEND_CAFES" (
   "CAFE_ID"
);

COMMIT;

-------------------------------------------------------------------
--------------------- add by LKS 2025/12/22 -----------------------
-------------------------------------------------------------------
DROP TABLE "USER_BEN";

CREATE TABLE "USER_BEN" (
   "BEN_ID"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "BEN_START"   DATE      NOT NULL,
   "BEN_END"   DATE      NOT NULL
);

COMMENT ON COLUMN "USER_BEN"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

ALTER TABLE "USER_BEN" ADD CONSTRAINT "PK_USER_BEN" PRIMARY KEY (
   "BEN_ID"
);

ALTER TABLE "USER_BEN" ADD CONSTRAINT "FK_MEMBER_TO_USER_BEN_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);


-------------------------------------------------------------------
--------------------- add by PYY 2025/12/20 -----------------------
-------------------------------------------------------------------
----------
-- 5) MEMBER: 전시의 경우 memberNo 10~15번 임의 사용  preset:
-- memberNo=1: 'user01@devlog.com'
-- memberNo=2: 'user02@devlog.com'
-- memberNo=3: 'user03@devlog.com'
-- memberNo=4: 'user04@devlog.com'
-- memberNo=5: 'user05@devlog.com'
----------
---------- [ LEVEL 테이블: MEMBER 상위 테이블 ]
SELECT * FROM "LEVELS";
SELECT SEQ_LEVEL_NO.NEXTVAL from dual; -- 시퀀스없으면 에러: ORA-02289: sequence does not exist
DELETE FROM "LEVELS"; 

-- 기존 시퀀스 삭제
DROP SEQUENCE SEQ_LEVEL_NO; 
-- 시퀀스 생성
CREATE SEQUENCE SEQ_LEVEL_NO START WITH 1 NOCACHE;

-- 샘플 계정 추가(레벨1 ~ 레벨7)
INSERT INTO "LEVELS" VALUES(SEQ_LEVEL_NO.NEXTVAL, 100, 'Lv1');
INSERT INTO "LEVELS" VALUES(SEQ_LEVEL_NO.NEXTVAL, 200, 'Lv2');
INSERT INTO "LEVELS" VALUES(SEQ_LEVEL_NO.NEXTVAL, 300, 'Lv3');
INSERT INTO "LEVELS" VALUES(SEQ_LEVEL_NO.NEXTVAL, 400, 'Lv4');
INSERT INTO "LEVELS" VALUES(SEQ_LEVEL_NO.NEXTVAL, 500, 'Lv5');
INSERT INTO "LEVELS" VALUES(SEQ_LEVEL_NO.NEXTVAL, 600, 'Lv6');
INSERT INTO "LEVELS" VALUES(SEQ_LEVEL_NO.NEXTVAL, 700, 'Lv7');
INSERT INTO "LEVELS" VALUES(SEQ_LEVEL_NO.NEXTVAL, 800, 'Lv8');
INSERT INTO "LEVELS" VALUES(SEQ_LEVEL_NO.NEXTVAL, 900, 'Lv9');
INSERT INTO "LEVELS" VALUES(SEQ_LEVEL_NO.NEXTVAL, 1000, 'Lv10');

SELECT * FROM "LEVELS";

COMMIT;

---------- [ MEMBER 테이블 예시 삽입]
SELECT * FROM MEMBER;
SELECT SEQ_MEMBER_NO.NEXTVAL from dual; -- 시퀀스없으면 에러: ORA-02289: sequence does not exist
DELETE FROM MEMBER; 

-- 기존 시퀀스 삭제
DROP SEQUENCE SEQ_MEMBER_NO; 
-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 NOCACHE;


-- 샘플 계정 추가
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01@devlog.com'
    , '$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u' --  not 'pass01!'
	, '유저일', '닉네임1', '0231532820'
    , '백엔드15년차', 'N', 'N'
    , './user.png', 'N', DEFAULT, DEFAULT
    , '나소개', 'github.com', 'notion.com'
    , DEFAULT, DEFAULT, 1);

-- 관리자계정
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02@devlog.com'
    , '$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u' --  not 'pass02!'
	, '유저이', '닉네임2', '01043214321'
    , '풀스택10년차', 'N', 'Y'
    , './user.png', 'N', DEFAULT, DEFAULT
    , '나소개', 'github.com', 'notion.com'
    , DEFAULT, DEFAULT, 2);
    
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03@devlog.com'
    , '$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u' --  not 'pass03!'
	, '유저삼', '닉네임3', '01043214321'
    , '프론트엔드5년차', 'N', 'N'
    , './user.png', 'N', DEFAULT, DEFAULT
    , '나소개', 'github.com', 'notion.com'
    , DEFAULT, DEFAULT, 3);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04@devlog.com'
    , '$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u' --  not 'pass04!'
	, '유저사', '닉네임4', '01043214321'
    , '프론트엔드1년차', 'N', 'N'
    , './user.png', 'N', DEFAULT, DEFAULT
    , '나소개', 'github.com', 'notion.com'
    , DEFAULT, DEFAULT, 4);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user05@devlog.com'
    , '$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u' --  not 'pass05!'
	, '유저오', '닉네임5', '01043214321'
    , '프론트엔드0년차', 'N', 'N'
    , './user.png', 'N', DEFAULT, DEFAULT
    , '나소개', 'github.com', 'notion.com'
    , DEFAULT, DEFAULT, 5);

COMMIT;

-- 로그인 체크 SQL
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICKNAME,
	MEMBER_TEL, MEMBER_CAREER, PROFILE_IMG, MEMBER_ADMIN 
	--TO_CHAR(M_CREATE_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') AS ENROLL_DATE 
FROM "MEMBER"
WHERE MEMBER_DEL_FL = 'N'
AND MEMBER_EMAIL = 'user01@devlog.com'
AND MEMBER_PW = 'pass01!'
ORDER BY MEMBER_NO;

SELECT * FROM MEMBER
ORDER BY MEMBER_NO;

-------------------------------------------------------------------
--------------------- add by LKS 2025/12/22 -----------------------
-- 1) 보드코드 테이블 데이터 추가
-- 2) REPORT_CODE, BANK_INFO, EMOJI 테이블 데이터 추가
-- 3) LEVELS 테이블 데이터 업데이트 & 추가
-------------------------------------------------------------------

-- 1) 보드코드 테이블 데이터 추가
INSERT INTO BOARDTYPE
(BOARD_CODE, BOARD_NAME, PARENTS_BOARD_CODE)
VALUES (1, 'blog', NULL);

INSERT INTO BOARDTYPE
(BOARD_CODE, BOARD_NAME, PARENTS_BOARD_CODE)
VALUES (2, 'itnews', NULL);

INSERT INTO BOARDTYPE
(BOARD_CODE, BOARD_NAME, PARENTS_BOARD_CODE)
VALUES (3, 'freeboard', NULL);

INSERT INTO BOARDTYPE
(BOARD_CODE, BOARD_NAME, PARENTS_BOARD_CODE)
VALUES (4, 'qna', NULL);

INSERT INTO BOARDTYPE
(BOARD_CODE, BOARD_NAME, PARENTS_BOARD_CODE)
VALUES (21, 'AI', 2);

INSERT INTO BOARDTYPE
(BOARD_CODE, BOARD_NAME, PARENTS_BOARD_CODE)
VALUES (22, '테크', 2);

INSERT INTO BOARDTYPE
(BOARD_CODE, BOARD_NAME, PARENTS_BOARD_CODE)
VALUES (23, 'IT기업', 2);

INSERT INTO BOARDTYPE
(BOARD_CODE, BOARD_NAME, PARENTS_BOARD_CODE)
VALUES (24, '게임', 2);

INSERT INTO BOARDTYPE
(BOARD_CODE, BOARD_NAME, PARENTS_BOARD_CODE)
VALUES (25, '과학', 2);

INSERT INTO BOARDTYPE
(BOARD_CODE, BOARD_NAME, PARENTS_BOARD_CODE)
VALUES (26, '우주', 2); 

COMMIT;

SELECT * FROM BOARDTYPE
ORDER BY BOARD_CODE;

-----------------------------------------------------
-- 2) REPORT_CODE, BANK_INFO, EMOJI 테이블 데이터 추가

INSERT ALL
INTO REPORT_CODE VALUES (1, '스팸 / 광고')
INTO REPORT_CODE VALUES (2, '욕설 / 비방 / 혐오')
INTO REPORT_CODE VALUES (3, '음란 / 선정적 내용')
INTO REPORT_CODE VALUES (4, '개인정보 노출')
INTO REPORT_CODE VALUES (5, '불법 정보')
INTO REPORT_CODE VALUES (6, '폭력적 / 잔혹한 내용')
INTO REPORT_CODE VALUES (7, '기타 커뮤니티 규칙 위반')
SELECT 1 FROM DUAL;

INSERT ALL
INTO BANK_INFO VALUES ('004', 'KB국민은행')
INTO BANK_INFO VALUES ('023', 'SC제일은행')
INTO BANK_INFO VALUES ('039', '경남은행')
INTO BANK_INFO VALUES ('034', '광주은행')
INTO BANK_INFO VALUES ('003', '기업은행')
INTO BANK_INFO VALUES ('011', '농협')
INTO BANK_INFO VALUES ('031', '대구은행')
INTO BANK_INFO VALUES ('032', '부산은행')
INTO BANK_INFO VALUES ('002', '산업은행')
INTO BANK_INFO VALUES ('045', '새마을금고')
INTO BANK_INFO VALUES ('007', '수협')
INTO BANK_INFO VALUES ('088', '신한은행')
INTO BANK_INFO VALUES ('048', '신협')
INTO BANK_INFO VALUES ('081', '하나은행')
INTO BANK_INFO VALUES ('020', '우리은행')
INTO BANK_INFO VALUES ('071', '우체국')
INTO BANK_INFO VALUES ('037', '전북은행')
INTO BANK_INFO VALUES ('012', '축협')
INTO BANK_INFO VALUES ('090', '카카오뱅크')
INTO BANK_INFO VALUES ('089', '케이뱅크')
INTO BANK_INFO VALUES ('027', '한국씨티은행')
INTO BANK_INFO VALUES ('092', '토스뱅크')
SELECT 1 FROM DUAL;

ALTER TABLE EMOJI
MODIFY EMOJI VARCHAR2(6);

INSERT ALL
INTO EMOJI VALUES (1, '❤️')
INTO EMOJI VALUES (2, '👍')
INTO EMOJI VALUES (3, '😀')
INTO EMOJI VALUES (4, '😂')
INTO EMOJI VALUES (5, '😮')
INTO EMOJI VALUES (6, '😡')
SELECT 1 FROM DUAL;


-----------------------------------------------------
-- 3) LEVELS 테이블 데이터 업데이트 & 추가

UPDATE LEVELS SET REQUIRED_TOTAL_EXP = 0,    TITLE = '초보자'
WHERE LEVEL_NO = 1;

UPDATE LEVELS SET REQUIRED_TOTAL_EXP = 100,  TITLE = '견습 개발자'
WHERE LEVEL_NO = 2;

UPDATE LEVELS SET REQUIRED_TOTAL_EXP = 300,  TITLE = '연습생'
WHERE LEVEL_NO = 3;

UPDATE LEVELS SET REQUIRED_TOTAL_EXP = 600,  TITLE = '신입 개발자'
WHERE LEVEL_NO = 4;

UPDATE LEVELS SET REQUIRED_TOTAL_EXP = 1000, TITLE = '튜토리얼 완료'
WHERE LEVEL_NO = 5;

UPDATE LEVELS SET REQUIRED_TOTAL_EXP = 1500, TITLE = '초급 개발자'
WHERE LEVEL_NO = 6;

UPDATE LEVELS SET REQUIRED_TOTAL_EXP = 2100, TITLE = '기능 사용자'
WHERE LEVEL_NO = 7;

UPDATE LEVELS SET REQUIRED_TOTAL_EXP = 2800, TITLE = '로직 사용자'
WHERE LEVEL_NO = 8;

UPDATE LEVELS SET REQUIRED_TOTAL_EXP = 3600, TITLE = '문제 해결가'
WHERE LEVEL_NO = 9;

UPDATE LEVELS SET REQUIRED_TOTAL_EXP = 4500, TITLE = '주니어 개발자'
WHERE LEVEL_NO = 10;


--INSERT INTO LEVELS VALUES (1,   0,     '초보자');
--INSERT INTO LEVELS VALUES (2,   100,   '견습 개발자');
--INSERT INTO LEVELS VALUES (3,   300,   '연습생');
--INSERT INTO LEVELS VALUES (4,   600,   '신입 개발자');
--INSERT INTO LEVELS VALUES (5,   1000,  '튜토리얼 완료');
--INSERT INTO LEVELS VALUES (6,   1500,  '초급 개발자');
--INSERT INTO LEVELS VALUES (7,   2100,  '기능 사용자');
--INSERT INTO LEVELS VALUES (8,   2800,  '로직 사용자');
--INSERT INTO LEVELS VALUES (9,   3600,  '문제 해결가');
--INSERT INTO LEVELS VALUES (10,  4500,  '주니어 개발자');

INSERT INTO LEVELS VALUES (11,  5500,  '숙련자');
INSERT INTO LEVELS VALUES (12,  6600,  '기능 숙련자');
INSERT INTO LEVELS VALUES (13,  7800,  '코드 숙련자');
INSERT INTO LEVELS VALUES (14,  9100,  '실전 숙련자');
INSERT INTO LEVELS VALUES (15, 10500,  '실무 숙련자');

INSERT INTO LEVELS VALUES (16, 12000,  '중급 개발자');
INSERT INTO LEVELS VALUES (17, 13600,  '설계 참여자');
INSERT INTO LEVELS VALUES (18, 15300,  '안정성 담당');
INSERT INTO LEVELS VALUES (19, 17100,  '품질 담당');
INSERT INTO LEVELS VALUES (20, 19000,  '베테랑 개발자');

INSERT INTO LEVELS VALUES (21, 21000,  '고급 개발자');
INSERT INTO LEVELS VALUES (22, 23100,  '시스템 전문가');
INSERT INTO LEVELS VALUES (23, 25300,  '문제 해결 전문가');
INSERT INTO LEVELS VALUES (24, 27600,  '핵심 멤버');
INSERT INTO LEVELS VALUES (25, 30000,  '시니어 개발자');

INSERT INTO LEVELS VALUES (26, 32500,  '마스터');
INSERT INTO LEVELS VALUES (27, 35100,  '그랜드 마스터');
INSERT INTO LEVELS VALUES (28, 37800,  '전설의 개발자');
INSERT INTO LEVELS VALUES (29, 40600,  '서버 네임드');
INSERT INTO LEVELS VALUES (30, 43500,  'Devlog 레전드');

COMMIT;


